version: 2.1
jobs:
  build:
    docker:
      - image: circleci/10.14.2-jessie
        auth:
          username: 1rswe
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: npm build
  test:
    docker:
      - image: circleci/10.14.2-jessie
        auth:
          username: 1rswe
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: npm test
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
